data = [
    ('AMP', 'Tracking'),
    ('AMP', 'Business Insights'),
    ('AMP', 'AMP Genome'),
    ('AMP', 'Dataset Configurator'),
    ('AMP', 'Forecasting Tool'),
    ('AMP', 'ABI'),
    ('AMP', 'Diagnostic Modeling'),
    ('AMP', 'Constrained Regression'),
    ('AMP', 'Bulk Upload'),
    ('AMP', 'Company'),
    ('Agile Learning', 'Agile Dataset Management'),
    ('Agile Learning', 'Rollout'),
    ('Agile Learning', 'Iterate'),
    ('Agile Learning', 'Elasticities'),
    ('PROPHET', 'Strategic Planner'),
    ('PROPHET', 'Tactical Planner'),
    ('PROPHET', 'Campaign Planner'),
    ('PROPHET', 'Insights Dashboard'),
    ('PROPHET', 'Insights Reports'),
    ('ADAPTA', 'Data Scorecard'),
    ('ADAPTA', 'Adapta Max Scheduler'),
    ('ADAPTA', 'Adapta Max'),
    ('ADAPTA', 'ADAPTA Upload'),
    ('ADAPTA', 'ADAPTA Review'),
    ('ADAPTA', 'ADAPTA Review Dataset Configurator'),
    ('ROI Genome', 'Insights Max'),
    ('ROI Genome', 'Genome Taxonomy Trackers'),
    ('Other', 'GPS'),
    ('Other', 'Product / QA user'),
    ('Strategic Planner', 'Fighting - Full access'),
    ('Strategic Planner', 'Fighting - View only'),
    ('Tactical Planner', 'Tactical Dataset Management'),
    ('Campaign Planner', 'Campaign Planner Dataset Management'),
    ('Insights Dashboard', 'Insights Dashboard Configurator'),
    ('Insights Reports', 'Portal Admin')
]
